apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-playground
  description: Terraform things.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: terraform
  owner: platform-engineering
  lifecycle: experimental
